apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: global-ingress
spec:
  profile: empty
  components:
    ingressGateways:
    - name: global-ingress
      enabled: true
      namespace: istio-system
      label:
        ingress: global
      k8s:
        service:
          type: LoadBalancer  # This will request an external IP

#Layers of Istio Traffic:

# 1. Gateway-loadbalancer
  # Incoming traffic from the internet is first received by the Gateway Loadbalancer.

# 2. Gateway-configuration
  # Traffic types allowed by the Gateway are defined in the Gateway Configuration.

# 3. Virtual-Service
  #Virtual service maps application services to it's routes and can loadbalance and map service destinations using the match field.

# 4. Application-Service


# 5. Service-Subsets


# 6. Application