---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp
  namespace: monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - istio-system
  selector:
    matchLabels:
      ingress: global
  endpoints:
    - port: metrics
      path: /stats/prometheus
